In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a[0])

1


In [5]:
a[0] = 5
a.shape

(3,)

In [7]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
b.shape
b.ndim
b.size

6

In [9]:
b[0,0]

np.int64(1)

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.random((2,2))

array([[0.28123515, 0.15451249],
       [0.30595703, 0.90005894]])

In [22]:
a = np.array([10,20,30,40,50])
a[1:4]

array([20, 30, 40])